#pragma once
#include <SFML/Window.hpp>
#include <SFML/Graphics.hpp>
#include "Functions.h"
#include "Circle.h"
#include "CircleRGB.h"
#include "CircleHSV.h"
#include "CircleHSL.h"
#include "CircleCMY.h"